### ISSUE TITLE
Zoom In/Out of Node Window

### ISSUE THREAD

**Issue by Amechwarrior** [CWolfs/ConverseTek#49]
It would be nice to be able to zoom in and out of the node tree either with a hotkey or key(SHIFT or CTRL) + mouse scroll wheel.

**Comment by CWolfs** [comment]
I'm working on this feature at the moment. It'll be in the v1.4 release. I've got it working but would like to make the scrollbar a little less janky when it zooms, and add a 'reset zoom' button or hotkey.

It's controlled with 'CTRL' + mouse wheel scroll.

![ConverseTek_Zoom](https://user-images.githubusercontent.com/7622361/233966482-cc3ce660-ec85-4a3b-baea-44269a8a2dba.gif)

**Comment by CWolfs** [comment]
Current hard zoom in and out max levels look like this:

![ConverseTek_0uoAwCUTpP](https://user-images.githubusercontent.com/7622361/233967800-d1d6e189-6cbe-4a6c-8b83-660378166efa.png)
![ConverseTek_ogweO40141](https://user-images.githubusercontent.com/7622361/233967808-2c018acc-ecc9-4bf2-afb9-303b4ffd4f33.png)

**Comment by CWolfs** [comment]
In `develop`.
