### ISSUE TITLE
Copied nodes use original text instead of updated values

### ISSUE THREAD

**Issue by IceRaptor** [CWolfs/ConverseTek#53]
I've created a convo with Sumire that have 4 nodes, one for heavy, light, medium and no aerospace wings. The medium and no wing nodes were created as copies of the heavy node. When they display in game, they display the heavy node text instead of their actual text.

I've attached the conversation so you can see the structure contains the right nodes, but that's not what the game displays:

[simGameConversations.zip](https://github.com/CWolfs/ConverseTek/files/2870611/simGameConversations.zip)

**Comment by IceRaptor** [comment]
Images to show the bug:
![image](https://user-images.githubusercontent.com/96743/52880763-e283f200-3130-11e9-9d17-3eae8a19a6a9.png)

![image](https://user-images.githubusercontent.com/96743/52880789-faf40c80-3130-11e9-8578-fda59e6c0017.png)

**Comment by CWolfs** [comment]
I believe this is related to #64

**Comment by CWolfs** [comment]
Fixed in `develop`.

**Comment by CWolfs** [comment]
Tested this in all combinations I can think of and it works without problems now.

If you have any old conversations that are broken you'll be able to load it up in v1.4 and it will be autofixed for any of the issues on save to JSON or the binary format.
