### ISSUE TITLE
Add functionality to load conversation from JSON.

### ISSUE THREAD

**Issue by mjbroekman** [CWolfs/ConverseTek#57]
I love the functionality you have to export a conversation as JSON, because sometimes it's easier to read it that way. Would it be possible to add functionality to do the reverse so that conversations can be written out in JSON and then loaded by ConverseTek and saved as a bytes file?

**Comment by CWolfs** [comment]
This is actually a feature I was working on a while ago before I took a break. It's almost finished and will come in the next release 🙂.

**Comment by CWolfs** [comment]
In `develop`.
