### ISSUE TITLE
Just some QoL suggestions

### ISSUE THREAD

**Issue by ajkroeg** [CWolfs/ConverseTek#67]
Just a couple minor QoL enhancements that may or may not be easily doable.

1. Have ConverseTek remember working directory used in the previous session, or integrate the "Open Folder" dialogue with Explorer (e.g. show Quick Access, etc).

2. Keep changes to loaded conversations when switching from conversation to another, but don't save externally until "save" button is clocked. So if I edit conversation A, then click over to glance at Conversation B, I shouldn't lose my changes to A unless I exit ConverseTek without saving.

**Comment by CWolfs** [comment]
Thanks for the suggestions (necro-reply incoming). I'm extracting these QoL suggestions into their own issues to better track them.

1. Quick links / bookmarks will be introduced to help this issue. I won't be able to integrate the explorer style options easily without developing it myself. Tracking it here https://github.com/CWolfs/ConverseTek/issues/80 and https://github.com/CWolfs/ConverseTek/issues/92
 
2. Tracking this here now https://github.com/CWolfs/ConverseTek/issues/91
